### ISSUE TITLE
Cannot read property 'getBuffer' of undefined

### ISSUE THREAD

**Issue by wynstep** [singularityhub/language-singularity#11]
Hello there, 
I just want to report an error I have once installed language singularity on my atom.

[Enter steps to reproduce:]

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.0.1
**Thrown From**: [language-singularity](ssh://git@github.com/singularityhub/language-singularity) package 2.1.0

### Stack Trace

TypeError: Cannot read property 'getBuffer' of undefined

```
At Cannot read property 'getBuffer' of undefined

TypeError: Cannot read property 'getBuffer' of undefined
    at Object.setGrammar (/packages/language-singularity/lib/main.js:36:29)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191492)
    at Workspace.open (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:433138)
    at ao (/packages/markdown-preview-plus/dist/main.js:1:209821)
```

### Commands

```
     -0:18.1.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-language-r 1.4.8 
ftp-remote-edit-plus 1.2.0 
language-singularity 2.1.0 
markdown-preview-plus 4.8.4 
```

**Comment by vsoch** [comment]
The traceback is pointing to the markdown-preview-plus - are you able to give the exact steps to reproduce the error? Does it happen without the markdown preview plus?

**Comment by wynstep** [comment]
Hey, thanks for your answer.
Yes, the error happens when I open the preview panel on markdown-preview-plus. It does not happen without the markdown preview plus.

**Comment by vsoch** [comment]
Perhaps open the issue on that plugin’s board then? If there is something to do back here, then I’d be happy to help.

**Comment by wynstep** [comment]
Okay, no problem. Could you please leave the issue open so I can come back to you when/if they reply?
